# Builds src/js/export/pdf-fonts.js: Outfit at the weights the drawings use, as static TrueType
# subsets (zlib, base64) with unicode -> glyph id and advance widths, for the vector PDF.
# Dev only: python3 tools/pdf-fonts.py   (needs fonttools + brotli)
import re, base64, io, json, zlib, sys
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools import subset
css=open('src/styles/fonts.css').read()
m=re.search(r"font-family:'Outfit';src:url\(data:font/woff2;base64,([^)]+)\)",css)
var=base64.b64decode(m.group(1))
CHARS=list(range(0x20,0x7f))+list(range(0xa0,0x100))+list(range(0x2010,0x2028))+list(range(0x2030,0x203b))+\
  [0x2190,0x2191,0x2192,0x2193,0x2212,0x2022,0x2009,0x2713,0x26a0,0x2248,0x2264,0x2265,0x221e,0x2032,0x2033]
out={}
for w in (400,500,600,700):
  f=TTFont(io.BytesIO(var))
  st=instancer.instantiateVariableFont(f,{'wght':w})
  b=io.BytesIO(); st.flavor=None; st.save(b); b.seek(0)
  f2=TTFont(b)
  opt=subset.Options(); opt.layout_features=['kern']; opt.name_IDs=['*']; opt.notdef_outline=True; opt.recalc_bounds=True
  opt.drop_tables+=['GSUB','GPOS','GDEF','STAT','DSIG']
  ss=subset.Subsetter(opt); ss.populate(unicodes=CHARS); ss.subset(f2)
  b2=io.BytesIO(); f2.save(b2); ttf=b2.getvalue()
  f3=TTFont(io.BytesIO(ttf))
  cmap=f3.getBestCmap(); order=f3.getGlyphOrder(); gid={n:i for i,n in enumerate(order)}
  hm=f3['hmtx'].metrics; upm=f3['head'].unitsPerEm
  u2g={}; wid={}
  for u,n in cmap.items(): u2g[u]=gid[n]
  for n,i in gid.items(): wid[i]=hm[n][0]
  hh=f3['hhea']; os2=f3['OS/2']; hd=f3['head']
  out[w]={'ttf':base64.b64encode(zlib.compress(ttf,9)).decode(),'len':len(ttf),'upm':upm,
    'asc':hh.ascent,'desc':hh.descent,'cap':getattr(os2,'sCapHeight',700),'bbox':[hd.xMin,hd.yMin,hd.xMax,hd.yMax],
    'u2g':u2g,'w':[wid.get(i,0) for i in range(len(order))]}
  print(w,len(ttf),'bytes',len(out[w]['ttf']),'b64',file=sys.stderr)
js='/* ===== generated by tools/pdf-fonts.py: Outfit for the vector PDF (zlib TrueType subsets) ===== */\nconst PDF_FONTS='+json.dumps(out,separators=(',',':'))+';\n'
open('src/js/export/pdf-fonts.js','w').write(js)
